apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-kisslog-backend
  namespace: kisslog
data:
  appsettings.json: |-
    {
        "Logging": {
            "LogLevel": {
                "Default": "Warning",
                "Microsoft": "Warning",
                "Microsoft.Hosting.Lifetime": "Warning"
            }
        },
        "ConfigurationFilePath": "Configuration/KissLog.json",
        "AllowedHosts": "*",
        "Kestrel": {
            "EndPoints": {
                "Http": {
                    "Url": "http://0.0.0.0:80"
                }
            }
        }
    }
