apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-kisslog-frontend
  namespace: kisslog
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Warning"
        }
      },
      "ApplicationType": "OnPremises",
      "AllowedHosts": "*",
      "Kestrel": {
        "EndPoints": {
          "Http": {
            "Url": "http://0.0.0.0:80"
          }
        }
      }
    }
