apiVersion: v1
kind: ConfigMap
metadata:
  name: kisslog-frontend
  namespace: kisslog
data:
  KissLog.json: |-
    {
      "ApplicationName": "KissLog",
      "StaticResourcesVersion": "4.0.0",
      "KissLogBackend.BasicAuth.Password": "_this_password_should_be_replaced_",
      "KissLog.License": "",
      "KissLogBackendUrl": "http://kisslog-backend",
      "KissLogFrontendUrl": "http://kisslog-frontend",
      "MediaDirectoryPath": "",
      "Database": {
        "Provider": "MySql",
        "ConnectionString": "server=kisslog-mariadb;port=3306;database=KissLog_Frontend_Dev;uid=root;password=pass;Charset=utf8;"
      },
      "Authorization": {
        "DefaultEmailDomain": "kisslog.net",
        "HS256Secret": "_ChangeThis_4H3Q935LLRG5TEPNVUYOQPRS0SXLT3ML_",
        "SessionCookie": {
          "IsPersistentFixedValue": null,
          "ExpireInMinutes": 10080
        },
        "ExternalIdentityProviders": {}
      },
      "Smtp": {
        "Host": "smtp.sendgrid.net",
        "Port": 587,
        "UserName": "",
        "Password": "",
        "EnableSsl": false,
        "From": {
          "Address": "support@kisslog.net",
          "DisplayName": "KissLog"
        }
      },
      "UserInterface": {
        "ForceAvatarSrc": null,
        "CreatePermalinkWithAnonymousAccess": {
          "IsEnabled": true,
          "ValidForSeconds": 7200
        },
        "Applications": {
          "LoadHowMany": 6
        },
        "Dashboard": {
          "ShowReferringSites": true
        }
      }
    }
