apiVersion: apps/v1
kind: Deployment
metadata:
  name: kisslog-mariadb
  namespace: kisslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pass"
        - name: MYSQL_DATABASE
          value: "KissLog_Frontend"
