apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- configmap-appsettings-kisslog-backend.yml
- configmap-appsettings-kisslog-frontend.yml
- configmap-kisslog-backend.yml
- configmap-kisslog-frontend.yml
- deployment-backend.yml
- deployment-frontend.yml
- deployment-mariadb.yml
- deployment-mongodb.yml
- service-backend.yml
- service-frontend.yml
- service-mariadb.yml
- service-mongodb.yml
